//
//  Localization.swift
//  Bookworm
//
//  Created by LUU THANH TAM on 2024/06/10.
//

import Foundation

struct Localized {
    static let Add = NSLocalizedString("Add", comment: "button title")
    static let Add_Edit_Link = NSLocalizedString("Add_Edit_Link", comment: "Add / Edit Link button")
    static let Add_Image = NSLocalizedString("Add_Image", comment: "Add Image button")
    static let Add_new_shortcut = NSLocalizedString("Add_new_shortcut", comment: "")
    static let Add_new_word = NSLocalizedString("Add_new_word", comment: "")
    static let Add_web_page_title = NSLocalizedString("Add_web_page_title", comment: "")
    static let Add_your_web_link = NSLocalizedString("Add_your_web_link", comment: "")
    static let Add_your_word_book_title = NSLocalizedString("Add_your_word_book_title", comment: "")
    static let All_words = NSLocalizedString("All_words", comment: "")
    static let All_words_lld = NSLocalizedString("All_words_lld", comment: "")
    static let An_error_occurred_while_loading_headlines = NSLocalizedString("An_error_occurred_while_loading_headlines", comment: "")
    static let An_error_occurred_while_loading_your_word = NSLocalizedString("An_error_occurred_while_loading_your_word", comment: "")
    static let Breaking_News = NSLocalizedString("Breaking_News", comment: "")
    static let Cancel = NSLocalizedString("Cancel", comment: "")
    static let Change_Image = NSLocalizedString("Change_Image", comment: "")
    static let Choose_your_wordbook = NSLocalizedString("Choose_your_wordbook", comment: "")
    static let Clear = NSLocalizedString("Clear", comment: "")
    static let Clear_all = NSLocalizedString("Clear_all", comment: "")
    static let Click_plus_button_or_start_browsing_your_webpages_to_add_new_words = NSLocalizedString("Click_plus_button_or_start_browsing_your_webpages_to_add_new_words", comment: "")
    static let Create = NSLocalizedString("Create", comment: "")
    static let Create_your_Wordbook = NSLocalizedString("Create_your_Wordbook", comment: "")
    static let Daily_story = NSLocalizedString("Daily_story", comment: "")
    static let Daily_Story = NSLocalizedString("Daily_Story", comment: "")
    static let Delete = NSLocalizedString("Delete", comment: "")
    static let Edit = NSLocalizedString("Edit", comment: "")
    static let Editing_shortcut = NSLocalizedString("Editing_shortcut", comment: "")
    static let Eg_Harry_Potter = NSLocalizedString("Eg_Harry_Potter", comment: "")
    static let Empty_Words = NSLocalizedString("Empty_Words", comment: "")
    static let Enter_your_web_link = NSLocalizedString("Enter_your_web_link", comment: "")
    static let Error_loading_headlines = NSLocalizedString("Error_loading_headlines", comment: "")
    static let Error_loading_word = NSLocalizedString("Error_loading_word", comment: "")
    static let Home = NSLocalizedString("Home", comment: "")
    static let Loading_content = NSLocalizedString("Loading_content", comment: "")
    static let Loading_url = NSLocalizedString("Loading_url", comment: "")
    static let Loading = NSLocalizedString("Loading", comment: "")
    static let No_history = NSLocalizedString("No_history", comment: "")
    static let No_Item = NSLocalizedString("No_Item", comment: "")
    static let Page_title = NSLocalizedString("Page_title", comment: "")
    static let Request_Balance = NSLocalizedString("Request_Balance", comment: "")
    static let Retry = NSLocalizedString("Retry", comment: "")
    static let Save_changes = NSLocalizedString("Save_changes", comment: "")
    static let Search = NSLocalizedString("Search", comment: "")
    static let Search_by_word = NSLocalizedString("Search_by_word", comment: "")
    static let Search_new_words = NSLocalizedString("Search_new_words", comment: "")
    static let Shortcut_list = NSLocalizedString("Shortcut_list", comment: "")
    static let Shortcuts = NSLocalizedString("Shortcuts", comment: "")
    static let Sorry_Could_not_find_this_word = NSLocalizedString("Sorry_Could_not_find_this_word", comment: "")
    static let Sorry_This_title_is_already_taken = NSLocalizedString("Sorry_This_title_is_already_taken", comment: "")
    static let Sorry_You_have_reached_the_request_limit = NSLocalizedString("Sorry_You_have_reached_the_request_limit", comment: "")
    static let Start_browsing_your_webpages_to_add_new_words = NSLocalizedString("Start_browsing_your_webpages_to_add_new_words", comment: "")
    static let Swipe_Action = NSLocalizedString("Swipe_Action", comment: "")
    static let Swipe_from_trailing_edge_to_edit_or_delete_your_shortcut = NSLocalizedString("Swipe_from_trailing_edge_to_edit_or_delete_your_shortcut", comment: "")
    static let Swipe_from_trailing_edge_to_edit_or_delete_your_wordBook = NSLocalizedString("Swipe_from_trailing_edge_to_edit_or_delete_your_wordBook", comment: "")
    static let Synonyms = NSLocalizedString("Synonyms", comment: "")
    static let Tap_on_this_button_to_add_your_Wordbook_name = NSLocalizedString("Tap_on_this_button_to_add_your_Wordbook_name", comment: "")
    static let Tap_on_this_plus_button_to_search_for_words = NSLocalizedString("Tap_on_this_plus_button_to_search_for_words", comment: "")
    static let This_is_an_indicator_for_your_request_remaining_balance = NSLocalizedString("This_is_an_indicator_for_your_request_remaining_balance", comment: "")
    static let Type_any_word = NSLocalizedString("Type_any_word", comment: "")
    static let Update = NSLocalizedString("Update", comment: "")
    static let Update_your_word_book_title = NSLocalizedString("Update_your_word_book_title", comment: "")
    static let Upload_your_webpage_icon = NSLocalizedString("Upload_your_webpage_icon", comment: "")
    static let Watch_AD_for_10_free_requests = NSLocalizedString("Watch_AD_for_10_free_requests", comment: "")
    static let Word_Book = NSLocalizedString("Word_Book", comment: "")
    static let Your_web_link = NSLocalizedString("Your_web_link", comment: "")
    static let Recently_Read = NSLocalizedString("Recently_Read", comment: "")
    static let Delete_word = NSLocalizedString("Delete_word", comment: "")
    static let Permanently_delete_your_word = NSLocalizedString("Permanently_delete_your_word", comment: "")
    static let Deleting_words_from_here_will_make_them_disappear_from_all_your_word_books_as_well = NSLocalizedString("Deleting_words_from_here_will_make_them_disappear_from_all_your_word_books_as_well", comment: "")
    static let Allow = NSLocalizedString("Allow", comment: "")
    static let Dont_ask_again = NSLocalizedString("Dont_ask_again", comment: "")
    static let Invalid = NSLocalizedString("Invalid", comment: "")
    static let Error = NSLocalizedString("Error", comment: "")
    static let Please_ensure_your_link_or_title_is_correct = NSLocalizedString("Please_ensure_your_link_or_title_is_correct", comment: "")
    static let This_title_or_link_is_already_exists = NSLocalizedString("This_title_or_link_is_already_exists", comment: "")
    static let Got_it = NSLocalizedString("Got_it", comment: "")
    static let Vocabulary_Review_Feature = NSLocalizedString("Vocabulary_Review_Feature", comment: "")
    static let The_vocabulary_review_feature_is_in_progress = NSLocalizedString("The_vocabulary_review_feature_is_in_progress", comment: "")
    static let We_are_working_hard_to_provide_it_as_soon_as_possible = NSLocalizedString("We_are_working_hard_to_provide_it_as_soon_as_possible", comment: "")
    static let Review = NSLocalizedString("Review", comment: "")
}
